# ***************** Universidad de los Andes ***********************
# ****** Departamento de Ingeniería de Sistemas y Computación ******
# ********** Arquitectura y diseño de Software - ISIS2503 **********
#
# Infraestructura para laboratorio de Circuit Breaker
# Elementos a desplegar:
# 1. Firewalls:
#    - cbd-services-apps
#    - cbd-services-apps-web
#    - cbd-circuit-breaker
#    - cbd-circuit-breaker-admin
#    - cbd-monitoring-db
# 2. Instancias MVs:
#    - cbd-kong-instance
#    - cbd-db-instance (postgreSQL instalado y configurado)
#    - cbd-alarms-app-(a-c) (Monitoring app instalada)
#    - cbd-monitoring-app (Monitoring app instalada y ejecutando)

resources:
# Database instance
- type: compute.v1.instance
  name: sprint-db-instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/isis2503-talleres-415604/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/isis2503-talleres-415604/global/networks/default
      networkIP: 10.128.0.12
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - cbd-monitoring-db
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo -u postgres psql -c "CREATE USER monitoring_user WITH PASSWORD 'isis2503';"
          sudo -u postgres createdb -O monitoring_user monitoring_db
          echo "host all all 0.0.0.0/0 trust" | sudo tee -a /etc/postgresql/12/main/pg_hba.conf
          echo "listen_addresses='*'" | sudo tee -a /etc/postgresql/12/main/postgresql.conf
          echo "max_connections=2000" | sudo tee -a /etc/postgresql/12/main/postgresql.conf
          sudo service postgresql restart